### ISSUE TITLE
Project TF328: (Possible) Issues

### ISSUE THREAD

**Issue by MHeinrichs** [terriblefire/tf328#2]
the line 

refresh_cas <= ~RW20 | ~chip_selected;

in fastmem.v line 141 is critical:

If you use the RAM constantly e.G. filling it with several MB of zeros it will not refresh, which can lead to faulty memory. I've designed som DRAMs controllers for 14MHz-Amigas aswell and tried this out: This WILL cause memory degeneration over some time. I suggest a separate timer for detecting the need of a refresh-cycle and wait until its finished.

**Comment by terriblefire** [comment]
Yes. But there is no way out of it with the stupid 6 state 020 setup. 

Its exactly the same setup as kipper2k. I'll alternate the ram bank refresh at some point.
