### ISSUE TITLE
Edu Arana 'Lite' CD32 Riser (Erratic and/or NO Keyboard Behavior Fix)

### ISSUE THREAD

**Issue by ooBumbleBeeoo** [terriblefire/tf328#6]
A few problems may occur with certain PS2 keyboards, I had already performed the PIC chip removal to get my keyboard running on the CD32 AUX socket before confirming the two methods below (I originally had no working keyboard when connected to the PS2 riser socket and ONLY the following activity on the CD32 AUX socket) -

- If you experience continuous '''''''''''''''''''' after pressing a key when the keyboard is plugged into the original CD32 AUX socket, then you will need to reverse two resistors on the riser to cure the issue (confirmed by Edu Arana).
R1 will need to be taken off of the board and swapped with R2, then R2 goes back in place of R1.

- If the above solution does not work for you, then the unsoldering and removal of the PIC chip (12f627) next to the PS2 socket will need to be performed (NOTE: you will have a useless PS2 riser socket after!).

THIS WILL BE UPDATED WHEN MORE INFORMATION BECOMES AVAILABLE.
I TAKE NO RESPONSIBILITY FOR YOUR ACTIONS, I AM MERELY STATING WHAT I DID TO CURE MY ISSUE.

Thanks,
Ant (ooBumbleBeeoo)

**Comment by terriblefire** [comment]
Probably best to add this to the Wiki rather than as issues,

**Comment by ooBumbleBeeoo** [comment]
I did EAB you about that, I have no idea how to?

**Comment by terriblefire** [comment]
you should have edit permissions https://github.com/terriblefire/tf328/wiki
