### ISSUE TITLE
RAM Speed could be improved. 

### ISSUE THREAD

**Issue by MHeinrichs** [terriblefire/tf328#8]
Hi,

I promissed you speed ups. Here they are: 2800-Dhystones in Sysinfo and about 2MB/s IDE-Speed.

Works fine with FastPage-Mode-RAMs but not with EDOs...

[tf528_ram_top.zip](https://github.com/terriblefire/tf328/files/1367210/tf528_ram_top.zip)

You can integrate these files in your code, if you like

Changelog: 

Top-Module:
RAM-Ready-signal added, to indicate, when RAM finished a refresh-cycle

IDE: 
IOR/W are not buffered but combinatorial to get rid of ide-read-errors
No Waitstate

RAM: 
Propper Refresh-cycle after 200-14Mhz-Clocks (<16us)
Best Efford Refresh-Cycles during access on other memory
RAS/CAS-Strobes clocked on neg/pos edges-> no waitstates (if no refresh)!

New:
(VERY) Simple Testbench

Known Bugs:
Since your design cannot control the WE-Llne to the rams, I rely on the fact, that most DRAMs refresh with WE=don't care. But some DRAMs need WE=HIGH during a CBR-refresh :(

Wishlist:
Connect the activity-Line to the IDE-Activity line for LED-flashing
Connect RAM-WE-Line to a CPLD
Connect IDE-WAIT to a CPLD
Merge these two CPLDs to a single TQFP100-one

Best regards Matthias

**Comment by terriblefire** [comment]
Wish you'd sent this last week. I committed a complete rewrite of the fastram yesterday and its confirmed working on all the chip types in use.

**Comment by terriblefire** [comment]
I also found IOR/IOW needed latched on the TF530 or it didnt work. Possibly something we can get away with here. Not too happy about using combinatorics for that. :/ perhaps latch on /AS?

**Comment by MHeinrichs** [comment]
Yes, your code works stable with my instable ISSI-EDO-RAM but it is damn slow!

My code uses two nasty tricks: first register-clocking on neg/pos edges and most RAMS need no setup-time for cas: you can stribe the address-mux and the cas-line at the same time...

**Comment by terriblefire** [comment]
I could incorporate that bit i guess. But if its not stable on all the ram chips i just get moaned at. :(

**Comment by MHeinrichs** [comment]
I have only two sets of different RAMs, perhaps, you look at the tweaks in my code and see whats fits to you.

**Comment by terriblefire** [comment]
For the parts other than the RAM i will look for sure. I removed some wait states for the Gayle register access already etc. IOR/IOW I will test and see what comes up. 

For the RAM ... hmmmm. I am torn. Yes i knew i was adding extra states in (and i tried to avoid them with the original firmware).... CAS setup times are published at 5-10ns which might be ok inside a single CPLD but going between 2 cplds it might be too tight. 

I could move that out to a different always block.. The refresh i have is pretty much equiv to yours now. I could make more use of both clock edges. but first i wanted stable.

**Comment by terriblefire** [comment]
I am almost tempted to have an "alternative"/"speedy" firmware that people can test at their own risk and have a boring stable reliable version as stock.

**Comment by MHeinrichs** [comment]
BAsed on your code I coded two versions:

[tf328_ram_top.zip](https://github.com/terriblefire/tf328/files/1377225/tf328_ram_top.zip)

The 0WS-File seems to work only with FP-DRAMS and brings ~2800 stones
The 1WS-File seems to work only with FP and EDO-DRAMS and brings ~2400 stones

**Comment by eabsolidcore** [comment]
Regarding 0WS specifically as 1WS worked fine for me on ISSI.

The Settlers 1.5 WHDLoad throws me "Exception "Illegal Instruction" ($10) at ($5CA904) ExpMem ($16904) occured."

No idea if it's relative to firmware or not, hopefully, you can test and get back to me. 

Chris

**Comment by eabsolidcore** [comment]
Further more, 1WS works fine on alliance ram on the settlers at 2400 stones, 0WAS doesn't for me regarding systest:

https://i.imgur.com/Y9QseIg.jpg

It may be a faulty ram here but why systest doesn't pick it up on stock firmware? hmmm

**Comment by terriblefire** [comment]
Quick word. would appreciate it if the product code was changed for different firmware types. So the ESM menu makes it obvious.

**Comment by eabsolidcore** [comment]
Update: ignore my reports - it was a false alarm, the ram cpld - ram lines were dry.  soldered them good and proper , interestingly WS1 and Stock didn't flag up the same issues however WS0 does indeed push the ram so that's probably why, either way the culprit was mine not firmware/ram. To finalize WS0 works on alliance, WS1 also, and Stock.

**Comment by eabsolidcore** [comment]
Update #2 : So I thought it was fixed but then memory tests failed again on systest at 0x680000 - 0x68ffff- possibly IC3, strangely flowing cpld/ ram IC's only improved the stability but not the entire situation. I'm assuming 1 of the alliance IC's is not capable of running on the 0WS firmware however 1WS is fine on systest.

Will leave it to you MHeinrichs to figure it out, if you need me to try any firmware let me know. Good job regardless. 

Chris.

**Comment by terriblefire** [comment]
This sounds like the original issue i had with the HY5118160 chips. Seems the higher memory locations werent getting refreshed properly.

**Comment by terriblefire** [comment]
I basically figured out that some of the ram do not like the timings we were trying use it with even though they meet the specs .

**Comment by eabsolidcore** [comment]
Sounds like that is the case mate. Will be interested to hear if you try the firmware on your alliance populated boards if and when you get time but obviously don't take the whole day out over it like I have hehe... It's been a fun ride but I'll stick to 1ws firmware on this alliance for now and have a play.
However, I did notice the settlers ran really fricking fast on 0ws 'when it worked'.

**Comment by terriblefire** [comment]
Will be building an alliance ram board soon.

**Comment by terriblefire** [comment]
Ok. Decided that the TF328 is not about performance. If i had designed it for that then it would have an 030. Closing is no interest in fixing this.

**Comment by kikendo** [comment]
Can this be forked as an alternate and further fixes be consolidated in github? EAB user solidcore had made some modifications to @MHeinrichs 's files but this is all residing in google drives and stuff and isn't optimal.
