### ISSUE TITLE
Circuit desing path thickness

### ISSUE THREAD

**Issue by gitowiec** [terriblefire/tf328#9]
Is it possible to change thickness of the circuit's path to 0.2mm? 
Same with the via's (or holes, IDK - they said they don't do 0.35/0.75mm) 
It seems that there is a problem if I would like to outsource printing to a printing house.
One said that they only print path 0.2mm and thicker, another says that 0.15 is prototype...
I am sorry about my ignorance, I am a total newbie in this matter.

**Comment by terriblefire** [comment]
Sorry, Board is designed to 6mil DRC. I don’t want to change that.

**Comment by terriblefire** [comment]
So the board is designed to 6-6-6 DRC. To change that would need a complete reroute. I have no desire to do that so that a few people can use a slightly cheaper boardhouse. I leave the pain of rerouting to someone who values their money less than the 100+ hours needed to reroute the board.
